GET http://localhost:5000/api/tasks

###
GET http://localhost:5000/api/tasks/6526abc573b1b78a0eef4439

###
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
    "title": "Clase de Python",
    "description": "Curso intensivo de Python a las 15.00h"
}

###
PUT http://localhost:5000/api/tasks/6526abc573b1b78a0eef4439
Content-Type: application/json

{
    "title": "Clase de python",
    "description": "Clase de Python el miercoles a las 18.00h"
}

###
DELETE http://localhost:5000/api/tasks/6526abc573b1b78a0eef4439